name: sample-otel-stack
services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-storage:/prometheus
    # Already got entrypoint
    command: ["--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus", "--enable-feature=remote-write-receiver"]

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasources:/etc/grafana/provisioning/datasources/
    depends_on:
      - prometheus
  
  alloy:
    image: grafana/alloy:v1.0.0
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
    depends_on:
      - prometheus


volumes:
  grafana-storage: {}
  prometheus-storage: {}